# Recommended production deployment (Streamable HTTP mode)
services:
  playwright-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/aakashh242/mcp-playwright:latest
    container_name: playwright-mcp-server
    stdin_open: true
    tty: true
    command: ["--http", "--listen", "0.0.0.0", "--port", "8000", "--path", "/mcp", "--host-name", "<your-dockerhost-host-name>"]
    ports:
      - "8000:8000"
    environment:
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
    volumes:
      - ./data/app-data:/app/data
      - ./data/resource-data:/data
